---
title: Statistical Programming Workshop
output: 
    html_document:
      theme: 
       bootswatch: united
knit: >
  (function(input_file, encoding) {
    metadata <- rmarkdown::yaml_front_matter(input_file)
    output_file <- "index"
    rmarkdown::render(input = input_file, output_file = output_file)
  })
---

```{=html}
<style type="text/css">

h1.title {
  font-size: 80px;
  color: #E85811;
  text-align: center;
}
body, td {
   font-size: 20px;
}
pre {
  font-size: 20px
}

</style>
```

------------------------------------------------------------------------

## Schedules & Recordings {.tabset .tabset-fade .tabset-pills}

### 📔 Workshop Schedules

-   [**Year 2024**]{style="color:#E85811"}

| Topics                                 | Lecturer      | Date       |
|----------------------------------------|---------------|------------|
| SAS Macro for comparing RTF            | Sachiel Li    | 2024-05-09 |
| SAS Macro for comparing RTF Updated    | Sachiel Li    | 2024-05-23 |
| [Define by P21](https://innocarepharma-my.sharepoint.cn/:p:/g/personal/tao_xiang_innocarepharma_com/Ea0UYCBFN1hErDALSGGwp3QBr3AujmroIZySXj4oZw9o-A?e=T8hUgr)                          | Rolland Luo   | 2024-06-05 |
| AE Narrative Tools Sharing             | Junjie Lang   | 2024-06-12 |
| [Clinical Reports with R](Clinical_Report_With_R.html)                | Tao Xiang     | 2024-07-26    |
| Figure Library - Spider Plot           | Jie Wang      | 2024-08-30    |
| R Basics                               | Tao Xiang     | 2024-09    |
| Figure Library - PK Concentration Plot | Binhan Chen   | 2024-10    |
| P21 Validation rules Discussion        | Menglian Ding | 2024-11    |
| Efficiency tools introduction          | Junjie Lang   | 2024-12    |

-   [**Year 2023**]{style="color:#E85811"}

| Topics                                 | Lecturer      | Date       |
|----------------------------------------|---------------|------------|
| [Introduction to SAS Graphic Template Language](https://innocarepharma-my.sharepoint.cn/:p:/g/personal/tao_xiang_innocarepharma_com/EdqBtZIM0wVIu9_Yys84Nc0B6vKNwcQWBGaqzs_oCDJ3RA?e=3TI2bi) | Tao Xiang   | 2023-09-28 |
| GTL Swimmer Plot  | Jie Wang    | 2023-11-20 |
| [Forest Plot with GTL](https://innocarepharma-my.sharepoint.cn/:p:/g/personal/tao_xiang_innocarepharma_com/EWNbQ1h3ghZPnQPskypD0skB9g44BvEeLbZLKK2J4cNkww?e=qK7t5N)                          | Rolland Luo | 2023-12-14 |
| [K-M Curve Plot with GTL](https://innocarepharma-my.sharepoint.cn/:p:/g/personal/tao_xiang_innocarepharma_com/ESbYSkBBe-hDjgG7c3L6zUgBOA0lB_D1p-eMgCvbVbdQEA?e=6VTEMw)                       | Binhan Chen | 2023-12-28 |
| DILI - Time course plot | Sachiel Li  | 2024-01-04 |

### 🎥 Recordings

-   [2023-09-28_Introduction of GTL](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EQJh4u2BXqtCpN8s5mb3p_0B5thsgsVBRDncbuwY9XAoiA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=GX0kxO)

-   [2023-11-20_GTL Swimmer Plot](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/Eag4sguefyVGm4jkKNt_n_oBubpOmtvqqyjCWYyT66xX1Q?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=I2DEgr)

-   [2023-12-14_Forest Plot with GTL](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EdOBLjcZiZRHld3mNIHdbtkB-eQpKsRiifywwTadD4aoHg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=aZ1JCR)

-   [2023-12-28_K-M Curve Plot with GTL](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EVJCq9g5v7dMoZwOt4YfrL4BlakkOffnOD6_lXlS7jxF9w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=4s0dfH)

-   [2024-01-04_DILI - Time course plot](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/ES59m4cb6F9LggI0mvi59RYBhA2vvMUC-Bf01coOPJ1p8g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=S4cmde)

-   [2024-05-09_SAS Macro for comparing RTF Part 1](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EYnQpoqpsJJOvLvybGhoMCABiJKo9HiMDyP8K9PlhiYjUA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=mWLMYn) & [2024-05-23_Part 2](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/ERuIIbShzYJMrVewjOqtVIoBYHoXZR18rrPGDCvjH4aIqg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=PUKqSM)

-   [2024-06-05_Define by P21](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EVQe_eUi5BhEmrLTU8R6RXkBgWA1TOXY6neH_kVQL2TOig?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=14Tcdx)

-   [2024-06-12_AE Narrative](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/EbKcPaakBd5KrYCEgXGF-HwB1Og5Ee8jYq8gEvRANMk2XQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=O1DqaD)

-   [2024-07-26_Clinical Report with R](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/Eb1IqTQF7nZGrPteKfIhamcBMDhq4dSTfYdlVjsBLLzHrg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=2fKZeg)

-   [2024-08-30_GTL Spider Plot](https://innocarepharma-my.sharepoint.cn/:v:/g/personal/tao_xiang_innocarepharma_com/ETyuFz8MSR5OpzRoa0b4PckB1aVXJk9F80Aviw6pxdiNuw?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view)